# build stage
FROM cdcgov/maven:fdns as builder

COPY . /usr/src/app
RUN mvn clean package

# run stage
FROM openjdk:8-jre-alpine

ARG REPORTING_PORT
ARG COMBINER_URL
ARG OBJECT_URL
ARG REPORTING_FLUENTD_HOST
ARG REPORTING_FLUENTD_PORT
ARG REPORTING_PROXY_HOSTNAME
ARG KAFKA_BROKERS
ARG OAUTH2_ACCESS_TOKEN_URI
ARG OAUTH2_PROTECTED_URIS
ARG OAUTH2_CLIENT_ID
ARG OAUTH2_CLIENT_SECRET
ARG SSL_VERIFYING_DISABLE

ENV REPORTING_PORT ${REPORTING_PORT}
ENV COMBINER_URL ${COMBINER_URL}
ENV OBJECT_URL ${OBJECT_URL}
ENV REPORTING_FLUENTD_HOST ${REPORTING_FLUENTD_HOST}
ENV REPORTING_FLUENTD_PORT ${REPORTING_FLUENTD_PORT}
ENV REPORTING_PROXY_HOSTNAME ${REPORTING_PROXY_HOSTNAME}
ENV KAFKA_BROKERS ${KAFKA_BROKERS}
ENV OAUTH2_ACCESS_TOKEN_URI ${OAUTH2_ACCESS_TOKEN_URI}
ENV OAUTH2_PROTECTED_URIS ${OAUTH2_PROTECTED_URIS}
ENV OAUTH2_CLIENT_ID ${OAUTH2_CLIENT_ID}
ENV OAUTH2_CLIENT_SECRET ${OAUTH2_CLIENT_SECRET}
ENV SSL_VERIFYING_DISABLE ${SSL_VERIFYING_DISABLE}

COPY --from=builder /usr/src/app/target/fdns-ms-reporting-*.jar /app.jar

# pull latest
RUN apk update && apk upgrade --no-cache

# don't run as root user
RUN chown 1001:0 /app.jar
RUN chmod g+rwx /app.jar
USER 1001

ENTRYPOINT java -Dserver.tomcat.protocol-header=x-forwarded-proto -Dserver.tomcat.remote-ip-header=x-forwarded-for -jar /app.jar