version: '3.1'
services:
  zookeeper:
    ports:
      - "32181:32181"
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    ports:
      - "29092:29092"
    image: confluentinc/cp-kafka:3.2.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
  fdns-ms-stubbing:
    image: cdcgov/fdns-ms-stubbing
    ports:
      - "3002:3002" 