version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    ports:
      - "29092:29092"
    image: confluentinc/cp-kafka:3.2.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
  fluentd:
    image: fluent/fluentd
    ports:
      - "24224:24224"
  fdns-ms-reporting:
    image: cdcgov/fdns-ms-reporting
    environment:
      REPORTING_PORT: 8091
      REPORTING_FLUENTD_HOST: fluentd
      REPORTING_FLUENTD_PORT: 24224
      KAFKA_BROKERS: kafka:29092
      COMBINER_URL: http://fdns-ms-combiner:8085
      OBJECT_URL: http://fdns-ms-object:8083
  # NOTE: These services depend on additional FDNS containers running that may be difficult in a low memory environment
  # Please see the docker-compose.yml for more information on dependent services